rvm:
  - 2.1.0
  - 2.2.3
  - 2.4.1

gemfile:
  - gemfiles/AR_4.2.gemfile
  - gemfiles/AR_5.0.1.gemfile
  - gemfiles/AR_5.1.1.gemfile
  - gemfiles/Rails_4.2.gemfile
  - gemfiles/Rails_5.0.1.gemfile
  - gemfiles/Rails_5.1.gemfile

script: bundle exec rspec
